[build]
  base = "/"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://acsti-booking-api.onrender.com/api/:splat"  ← Change this
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
